import React from 'react';
import { Button } from '@/components/ui/button';

// Ultra-simple homepage with zero dependencies - emergency fallback
export const SimpleHomepage: React.FC = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6">
            Sheraa
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Sharjah Entrepreneurship Center - Empowering the next generation of entrepreneurs
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="bg-blue-600 hover:bg-blue-700 text-white">
              Launch Your Startup
            </Button>
            <Button size="lg" variant="outline">
              Join Our Community
            </Button>
          </div>
        </div>
        
        <div className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <h3 className="text-xl font-semibold mb-2">180+ Startups</h3>
            <p className="text-gray-600 dark:text-gray-300">Supported through our programs</p>
          </div>
          <div className="text-center">
            <h3 className="text-xl font-semibold mb-2">$248M+ Revenue</h3>
            <p className="text-gray-600 dark:text-gray-300">Generated by our startups</p>
          </div>
          <div className="text-center">
            <h3 className="text-xl font-semibold mb-2">1,900+ Jobs</h3>
            <p className="text-gray-600 dark:text-gray-300">Created in the ecosystem</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SimpleHomepage;