
import { saveAs } from 'file-saver';

// Helper function to get file extension
const getExtension = (fileType: string): string => {
  switch (fileType.toLowerCase()) {
    case 'html':
      return 'html';
    case 'markdown':
    case 'md':
      return 'md';
    case 'json':
      return 'json';
    case 'csv':
      return 'csv';
    default:
      return 'txt';
  }
};

// Template generators
const generateHTMLTemplate = (title: string, description: string): string => {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #333;
      border-bottom: 1px solid #ddd;
      padding-bottom: 10px;
    }
    .description {
      color: #666;
      font-style: italic;
      margin-bottom: 20px;
    }
    .content {
      margin-top: 30px;
    }
    .footer {
      margin-top: 50px;
      border-top: 1px solid #ddd;
      padding-top: 10px;
      font-size: 0.8em;
      color: #666;
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="description">${description}</div>
  
  <div class="content">
    <!-- Replace this section with your actual content -->
    <h2>Getting Started</h2>
    <p>This is a template for your ${title} document. Customize it according to your needs.</p>
    
    <h2>Main Section 1</h2>
    <p>Add your content here...</p>
    
    <h2>Main Section 2</h2>
    <p>Add more content here...</p>
  </div>
  
  <div class="footer">
    <p>Generated by Sheraa Resources | © ${new Date().getFullYear()} Sharjah Entrepreneurship Center</p>
  </div>
</body>
</html>`;
};

const generateMarkdownTemplate = (title: string, description: string): string => {
  return `# ${title}

_${description}_

## Getting Started

This is a template for your ${title} document. Customize it according to your needs.

## Main Section 1

Add your content here...

## Main Section 2

Add more content here...

---

Generated by Sheraa Resources | © ${new Date().getFullYear()} Sharjah Entrepreneurship Center`;
};

const generateJSONTemplate = (title: string, description: string): string => {
  return JSON.stringify({
    title,
    description,
    sections: [
      {
        title: "Getting Started",
        content: `This is a template for your ${title} document. Customize it according to your needs.`
      },
      {
        title: "Main Section 1",
        content: "Add your content here..."
      },
      {
        title: "Main Section 2",
        content: "Add more content here..."
      }
    ],
    metadata: {
      creator: "Sheraa Resources",
      createdAt: new Date().toISOString(),
      copyright: `© ${new Date().getFullYear()} Sharjah Entrepreneurship Center`
    }
  }, null, 2);
};

const generateCSVTemplate = (title: string): string => {
  return `Category,Title,Description,Priority,Status,Notes
Section 1,Item 1,Description for Item 1,High,In Progress,
Section 1,Item 2,Description for Item 2,Medium,Not Started,
Section 2,Item 3,Description for Item 3,Low,Completed,
Section 2,Item 4,Description for Item 4,High,Not Started,
,,,,,
Notes:,This is a template for ${title}.,Please customize according to your needs.,,,
`;
};

// Main download function
export const downloadResource = (
  title: string, 
  description: string, 
  fileType: 'html' | 'markdown' | 'json' | 'csv' = 'html'
): void => {
  try {
    let content: string;
    const fileName = `${title.replace(/\s+/g, '-').toLowerCase()}.${getExtension(fileType)}`;
    
    switch (fileType) {
      case 'html':
        content = generateHTMLTemplate(title, description);
        break;
      case 'markdown':
        content = generateMarkdownTemplate(title, description);
        break;
      case 'json':
        content = generateJSONTemplate(title, description);
        break;
      case 'csv':
        content = generateCSVTemplate(title);
        break;
      default:
        content = description;
    }
    
    // Create and download the file
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, fileName);
    
    console.log(`Downloaded ${fileName}`);
  } catch (error) {
    console.error('Error downloading resource:', error);
  }
};
