
import React from 'react';
import MainLayout from '@/components/layouts/MainLayout';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Download, Calendar, FileText } from 'lucide-react';

const ImpactReportsPage: React.FC = () => {
  const reports = [
    {
      title: "Sheraa Impact Report 2024",
      description: "A comprehensive overview of Sheraa's ecosystem achievements, startup success stories, and economic impact over the past year.",
      date: "March 2025",
      image: "/placeholder.svg",
      fileSize: "8.5 MB",
    },
    {
      title: "Sharjah Startup Ecosystem Report",
      description: "An in-depth analysis of Sharjah's growing startup ecosystem, key sectors, investment trends, and future opportunities.",
      date: "September 2024",
      image: "/placeholder.svg",
      fileSize: "12.3 MB",
    },
    {
      title: "Women Founders in Sharjah Report",
      description: "Highlighting the achievements and opportunities for women entrepreneurs in Sharjah's innovation ecosystem.",
      date: "July 2024",
      image: "/placeholder.svg",
      fileSize: "5.7 MB",
    },
    {
      title: "Sheraa Impact Report 2023",
      description: "Looking back at a transformative year of growth for Sheraa and its supported startups.",
      date: "February 2024",
      image: "/placeholder.svg",
      fileSize: "7.8 MB",
    },
  ];

  const impactMetrics = [
    { number: "180+", label: "Startups Supported" },
    { number: "$248M+", label: "Revenue Generated by Startups" },
    { number: "$171M+", label: "Capital Raised by Startups" },
    { number: "1,900+", label: "Jobs Created" },
    { number: "52%", label: "Women-Led Startups" },
    { number: "18,000+", label: "Youth Upskilled" },
    { number: "140+", label: "Ecosystem Partners" },
    { number: "71%", label: "Startup Survival Rate" },
  ];

  return (
    <MainLayout>
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto mb-12">
          <h1 className="text-4xl font-bold text-sheraa-primary mb-4">Sheraa Impact Reports</h1>
          <p className="text-lg text-gray-600">
            Discover the collective achievements of the Sheraa ecosystem and the impact of entrepreneurship in Sharjah. 
            Our impact reports provide comprehensive insights into our programs, startup successes, economic contributions, 
            and the growth of Sharjah's innovation ecosystem.
          </p>
        </div>
        
        {/* Key Metrics Section */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-8 text-center">Impact That Speaks Volumes</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {impactMetrics.map((metric, idx) => (
              <div key={idx} className="bg-white p-6 rounded-lg border border-gray-200 text-center hover:shadow-md transition-shadow">
                <div className="text-3xl font-bold text-sheraa-primary mb-2">{metric.number}</div>
                <div className="text-gray-600">{metric.label}</div>
              </div>
            ))}
          </div>
          <div className="mt-6 text-center text-gray-600">
            <p>
              These figures demonstrate the scale and effectiveness of Sheraa's programs and the significant economic 
              contribution of its supported ventures. The high survival rate and strong representation of women-led 
              startups underscore the quality and inclusivity of the support provided.
            </p>
          </div>
        </div>
        
        {/* Latest Report Feature */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-6">Latest Impact Report</h2>
          <Card className="overflow-hidden">
            <div className="grid grid-cols-1 lg:grid-cols-3">
              <div className="lg:col-span-1 bg-gray-200 h-full">
                <img 
                  src="/placeholder.svg" 
                  alt="2024 Impact Report Cover" 
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="lg:col-span-2 p-8">
                <div className="flex items-center gap-2 mb-3">
                  <Calendar size={16} className="text-sheraa-primary" />
                  <span className="text-gray-500 text-sm">Released: March 2025</span>
                </div>
                <h3 className="text-2xl font-bold mb-4">Sheraa Impact Report 2024</h3>
                <p className="text-gray-600 mb-6">
                  Our latest impact report showcases the remarkable achievements of Sheraa's ecosystem in 2024. Highlighting our 
                  supported startups' success stories, the economic impact of our programs, and the growth of Sharjah's 
                  entrepreneurial landscape. Discover how Sheraa continues to drive innovation and create opportunities for 
                  founders across the region.
                </p>
                <div className="flex flex-wrap gap-4">
                  <Button className="flex items-center gap-2">
                    <Download size={16} /> Download Report
                  </Button>
                  <Button variant="outline">View Online</Button>
                </div>
              </div>
            </div>
          </Card>
        </div>
        
        {/* Previous Reports */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold mb-6">Previous Reports</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {reports.slice(1).map((report, idx) => (
              <Card key={idx} className="overflow-hidden hover:shadow-md transition-shadow">
                <div className="h-48 bg-gray-200">
                  <img 
                    src={report.image} 
                    alt={report.title} 
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="p-6">
                  <div className="flex items-center gap-2 mb-3">
                    <Calendar size={14} className="text-sheraa-primary" />
                    <span className="text-gray-500 text-xs">{report.date}</span>
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{report.title}</h3>
                  <p className="text-gray-600 text-sm mb-4 line-clamp-2">{report.description}</p>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center text-xs text-gray-500">
                      <FileText size={14} className="mr-1" />
                      <span>{report.fileSize} PDF</span>
                    </div>
                    <Button variant="outline" size="sm">Download</Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
        
        {/* Request Custom Reports */}
        <div className="bg-sheraa-light p-8 rounded-lg max-w-3xl mx-auto text-center">
          <h2 className="text-2xl font-semibold mb-4">Need Specific Ecosystem Data?</h2>
          <p className="text-gray-700 mb-6">
            If you're a researcher, investor, or policymaker looking for specific data on Sharjah's 
            entrepreneurial ecosystem, we may be able to provide customized reports or insights.
          </p>
          <Button>Request Custom Data</Button>
        </div>
      </div>
    </MainLayout>
  );
};

export default ImpactReportsPage;
