import React from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, Users, DollarSign, Briefcase, Award, Globe } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

const ImpactMetricsSnapshot: React.FC = () => {
  const { t } = useLanguage();

  const metrics = [
    {
      icon: TrendingUp,
      value: '180+',
      label: t('impact.startups'),
      description: 'Supported through our programs',
      color: 'text-blue-600',
      bgColor: 'bg-blue-50'
    },
    {
      icon: DollarSign,
      value: '$248M+',
      label: t('impact.revenue'),
      description: 'Generated by our startups',
      color: 'text-green-600',
      bgColor: 'bg-green-50'
    },
    {
      icon: Briefcase,
      value: '1,900+',
      label: t('impact.jobs'),
      description: 'Created across the ecosystem',
      color: 'text-purple-600',
      bgColor: 'bg-purple-50'
    },
    {
      icon: Users,
      value: '52%',
      label: t('impact.women'),
      description: 'Breaking barriers together',
      color: 'text-pink-600',
      bgColor: 'bg-pink-50'
    },
    {
      icon: Award,
      value: '71%',
      label: t('impact.survival'),
      description: 'Well above global average',
      color: 'text-orange-600',
      bgColor: 'bg-orange-50'
    },
    {
      icon: Globe,
      value: '140+',
      label: t('impact.partners'),
      description: 'Driving innovation together',
      color: 'text-indigo-600',
      bgColor: 'bg-indigo-50'
    }
  ];

  return (
    <section className="py-16 bg-gradient-to-br from-gray-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Impact That Speaks Volumes
          </h2>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            We measure our success by the success of our founders and the growth of Sharjah's innovation ecosystem. 
            Our commitment translates into tangible results.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {metrics.map((metric, index) => (
            <motion.div
              key={metric.label}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all duration-300 border border-gray-100"
            >
              <div className="flex items-start space-x-4">
                <div className={`p-3 rounded-lg ${metric.bgColor}`}>
                  <metric.icon className={`h-6 w-6 ${metric.color}`} />
                </div>
                <div className="flex-1">
                  <div className={`text-2xl font-bold ${metric.color} mb-1`}>
                    {metric.value}
                  </div>
                  <div className="font-semibold text-gray-900 mb-1">
                    {metric.label}
                  </div>
                  <div className="text-sm text-gray-600">
                    {metric.description}
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="text-center mt-12"
        >
          <p className="text-gray-600 mb-6">
            These figures demonstrate the scale and effectiveness of Sheraa's programs and the significant economic contribution of our supported ventures.
          </p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="bg-sheraa-primary text-white px-8 py-3 rounded-lg font-semibold hover:bg-sheraa-primary/90 transition-colors"
          >
            Read Our Latest Impact Report
          </motion.button>
        </motion.div>
      </div>
    </section>
  );
};

export default ImpactMetricsSnapshot;