
import React from "react";
import { Card, CardContent } from "@/components/ui/card";

const ImpactNumbers = () => {
  return (
    <section className="py-16 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Our Impact</h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            We've helped entrepreneurs build innovative solutions and create economic value.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <ImpactCard 
            number="500+"
            label="Startups Supported"
            description="Entrepreneurs who have benefited from our programs and resources."
          />
          <ImpactCard 
            number="$50M+"
            label="Venture Capital Raised"
            description="Total funding raised by startups in our community."
          />
          <ImpactCard 
            number="2,500+"
            label="Jobs Created"
            description="Employment opportunities generated by our startups."
          />
          <ImpactCard 
            number="100+"
            label="Community Events"
            description="Workshops, talks, and networking opportunities hosted annually."
          />
        </div>
      </div>
    </section>
  );
};

interface ImpactCardProps {
  number: string;
  label: string;
  description: string;
}

const ImpactCard = ({ number, label, description }: ImpactCardProps) => {
  return (
    <Card className="border-none shadow-md hover:shadow-lg transition-shadow">
      <CardContent className="p-6 text-center">
        <div className="text-4xl font-bold text-sheraa-primary mb-2">{number}</div>
        <h3 className="text-lg font-medium mb-2">{label}</h3>
        <p className="text-sm text-gray-500">{description}</p>
      </CardContent>
    </Card>
  );
};

export default ImpactNumbers;
