// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgqjvwemxmmhdufjazpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncWp2d2VteG1taGR1ZmphenBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDcyNjYsImV4cCI6MjA2Mzc4MzI2Nn0.xSzLUV0i7HXV1iFoaWdjaK4ejthzBsWs9EmVEaKrQx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);